HW1
anton-kuvaldin/smart-home-2020 pull request #1
Opened 2020-10-06 18:25 UTC by megahard25

До конца задание выполнить не получилось, но очень надеюсь разобраться с помощью ваших замечаний и доделать задачу.

2020-10-09 14:00 UTC, a-ivanov requested changes

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B5%D1%81%D0%B8%D1%82%D0%B5-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D1%83-%D1%86%D0%B8%D0%BA%D0%BB%D0%B0-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%B2-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BB%D0%B0%D1%81%D1%81

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          String json = new String(Files.readAllBytes(Paths.get("smart-home-1.js")));
Добавьте интерфейс для чтения состояния дома с имплементацией для чтения из json.

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        this.processor = processor;
А где Application создается?

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        this.processor = processor;
И запускается?

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private final EventProcessorImpl processor;
В полях-зависимостях лучше использовать ссылку на интерфейс, а не на реализацию, чтобы можно было легко заменять имплементации зависимостей.

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessorImpl.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Нарушение OCP, как добавлять новые обработчики?

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    public void handleLightEvent(SensorEvent event) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%B4%D0%B5%D0%BB%D0%B5%D0%B3%D0%B8%D1%80%D1%83%D0%B9%D1%82%D0%B5-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D1%83-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0%D0%BC

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Door.java
> +                if (roomName.equals("hall")) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D1%8F%D0%B9%D1%82%D0%B5-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2-%D0%B8-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D1%83%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%BE%D0%BC%D0%B0

2020-10-09 14:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +public class Action {
Этот класс где-то сипользуется?

2020-10-19 19:03 UTC, megahard25 commented
@a-ivanov , был вынужден во многом обращаться за вдохновением к чужим кодам. Подумал, что лучше так и выполнить задание, чем не выполнить вообще. Если вас обеспокоит "похожесть" кода, смело вините только меня.

2020-10-28 14:27 UTC, closed without merging